# Generated by Django 3.2.3 on 2021-07-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='asset',
            field=models.CharField(default='Unit', max_length=100),
        ),
    ]
